### ISSUE TITLE
Anzeige von Bewertungen von Google Format anpassen

### ISSUE THREAD

**Issue by MichaelBinner1** [kerberk/tte#11]
Bewertungen sollten immer im Format X.X angezeigt werden. Derzeit gibt es auch nur X ohne Komma, dadurch sieht das Design nicht gut aus.

Bitte im Zuge dessen auch in den gelben Kasen immer klein "von google" schreiben.
![screenshot_20180122-105542 002](https://user-images.githubusercontent.com/35655916/35215062-6ec54e0e-ff63-11e7-88cf-1f7e047e77fd.png)

**Comment by kerberk** [comment]
Fixed
