### ISSUE TITLE
Bild in "Meine Deals" fehlt

### ISSUE THREAD

**Issue by MichaelBinner1** [kerberk/tte#6]
Ich habe fast immer bei der Seite "meine Deals" kein Bild (einmal von ca. 20mal war das Bild da)

**Comment by kerberk** [comment]
Nicht nachvollziehbar.  
Bei mir hat es bis jetzt in jedem Szenario funktioniert.  
Hier brauch ich nochmal mehr Infos:  
- Bist du nicht eingecheckt/eingecheckt?
- Kommst du von einer bestimmten Seite auf diese Seite?
- Läd er die Seite besonders lang?
- Kannst du das auch nochmal mit nem anderen Smartphone testen?

**Comment by MichaelBinner1** [comment]
kam nicht mehr vor
