### ISSUE TITLE
Auswahl auf Seite "Meine Restaurants" fehlerhaft

### ISSUE THREAD

**Issue by MichaelBinner1** [kerberk/tte#8]
Manchmal funktioniert es, manchmal nicht z.B. jetzt, eben die App manuell ausgemacht, neugestartet und dann auf Meine Restaurants. Jetzt bekomme ich bei jedem Restaurant welches ich auswähle nur eine leere weiße Seite.

...ich habe die Vermutung, dass hängt mit dem Login zusammen. Ich glaube ich war kurz in der App und war nicht eingeloggt. Denn nach ein 2 Minuten als ich immer diese weißen Screens hatte, kamm auf einmal der Login noch einmal. Das habe ich dann gemacht und es hat funktioniert. Vielleicht loggt er sich bei dem Auto-Loggin beim wiederöffnene der App teilweise nicht richtig wieder ein.

**Comment by kerberk** [comment]
Hier bitte nochmal testen.  
Bei mir tritt der Fehler nie auf, aber ich hab mal noch ne Sicherheitsabfrage eingebaut, damit der User hier auf jedenfall eingeloggt sein muss, um die Seite zu sehen.

**Comment by MichaelBinner1** [comment]
kam nicht mehr vor
